package Views;

import Controllers.Interface.Controller;
import Controllers.Interface.OperatorDashboardController;

/**
 *
 * @author xorigin
 */
public class OperatorDashboardView extends javax.swing.JFrame implements View{

    /**
     * Creates new form OperatorDashboardView
     * @param previousFrame
     */
    public OperatorDashboardView(javax.swing.JFrame previousFrame) {
        
        this.previousFrame = previousFrame;
        
        initComponents();
        
        this.setSpecialSettings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        FrameDescription = new javax.swing.JLabel();
        ViewBillsOfRegionButton = new javax.swing.JButton();
        ViewBillsCollectButton = new javax.swing.JButton();
        ActivationBoardButton = new javax.swing.JButton();
        CancelSubscripButton = new javax.swing.JButton();
        SignedAsField = new javax.swing.JLabel();
        SignedAsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operator Dashboard");
        setResizable(false);

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BackIcon.png"))); // NOI18N
        BackButton.setToolTipText("Log out");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        FrameDescription.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        FrameDescription.setText(" Operator Dashboard ");
        FrameDescription.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ViewBillsOfRegionButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        ViewBillsOfRegionButton.setText("View all bills of specific region");
        ViewBillsOfRegionButton.setToolTipText("Press to view all bills of specific region");
        ViewBillsOfRegionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBillsOfRegionButtonActionPerformed(evt);
            }
        });

        ViewBillsCollectButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        ViewBillsCollectButton.setText("View all bills and collect payment");
        ViewBillsCollectButton.setToolTipText("Press to view all bills and collect payment");
        ViewBillsCollectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBillsCollectButtonActionPerformed(evt);
            }
        });

        ActivationBoardButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        ActivationBoardButton.setText("Activation");
        ActivationBoardButton.setToolTipText("Press to open activation board");
        ActivationBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivationBoardButtonActionPerformed(evt);
            }
        });

        CancelSubscripButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        CancelSubscripButton.setText("Cancel Subscription");
        CancelSubscripButton.setToolTipText("Press to open customer cancel subscription");
        CancelSubscripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelSubscripButtonActionPerformed(evt);
            }
        });

        SignedAsField.setFont(new java.awt.Font("Chandas", 1, 14)); // NOI18N
        SignedAsField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignedAsField.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                SignedAsFieldAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        SignedAsLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        SignedAsLabel.setForeground(new java.awt.Color(51, 51, 51));
        SignedAsLabel.setText("Signed as: ");
        SignedAsLabel.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewBillsOfRegionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ActivationBoardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(CancelSubscripButton))
                                .addComponent(ViewBillsCollectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SignedAsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SignedAsField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(FrameDescription))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FrameDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignedAsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignedAsField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewBillsOfRegionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewBillsCollectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActivationBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelSubscripButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed

        this.dispose();
        this.previousFrame.revalidate();
        this.previousFrame.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ViewBillsOfRegionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBillsOfRegionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewBillsOfRegionButtonActionPerformed

    private void ViewBillsCollectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBillsCollectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewBillsCollectButtonActionPerformed

    private void ActivationBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivationBoardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActivationBoardButtonActionPerformed

    private void CancelSubscripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelSubscripButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelSubscripButtonActionPerformed

    private void SignedAsFieldAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_SignedAsFieldAncestorAdded

        this.SignedAsField.setText(this.controller.getLoggedInID());
    }//GEN-LAST:event_SignedAsFieldAncestorAdded

    @Override
    public final void setSpecialSettings() {
        
        this.setLocationRelativeTo(null);
        
        
    }
    
    @Override
    public void setController(Controller controller){
    
        this.controller = (OperatorDashboardController) controller;
    }
    
    @Override
    public javax.swing.JFrame getPreviousFrame(){
    
        return this.previousFrame;
    }
    
    private OperatorDashboardController controller;
    private final javax.swing.JFrame previousFrame;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActivationBoardButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CancelSubscripButton;
    private javax.swing.JLabel FrameDescription;
    private javax.swing.JLabel SignedAsField;
    private javax.swing.JLabel SignedAsLabel;
    private javax.swing.JButton ViewBillsCollectButton;
    private javax.swing.JButton ViewBillsOfRegionButton;
    // End of variables declaration//GEN-END:variables
}
