package Views.Admin;

import Controllers.Interface.AdministratorController;
import Controllers.Interface.Controller;
import Models.Enum.Role;
import Views.MainView;
import Views.View;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author xorigin
 */

public class DeleteAdministratorView extends javax.swing.JFrame implements View{

    /**
     * Creates new form DeleteAdministratorView
     * @param previousFrame
     */
    
    public DeleteAdministratorView(javax.swing.JFrame previousFrame) {
        
        this.setPreviousFrame(previousFrame);
        
        initComponents();
        
        this.setSpecialSettings(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        idField = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        roleField = new javax.swing.JLabel();
        confirmDeletionMessage = new javax.swing.JLabel();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete Administrator");
        setPreferredSize(new java.awt.Dimension(422, 222));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BackIcon.png"))); // NOI18N
        BackButton.setToolTipText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 58, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 188, 297, -1));

        id.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 194, 67, -1));

        idField.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        getContentPane().add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 85, 28));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel3.setText("ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 32, 28));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel5.setText("Role:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 45, 28));

        roleField.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        getContentPane().add(roleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 110, 28));

        confirmDeletionMessage.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        confirmDeletionMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmDeletionMessage.setText("Sure You Want to Delete This Administrator? ");
        getContentPane().add(confirmDeletionMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 340, 31));

        delete.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 138, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed

        this.dispose();
        this.previousFrame.revalidate();
        this.previousFrame.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        this.ID = this.controller.getTargetID(); 
        this.role = this.controller.getRole(this.ID); 
        this.idField.setText(this.ID);
        this.roleField.setText(this.role);
        this.confirmDeletionMessage.setText("Sure You Want To delete This "+ this.role + "?"); 
    }//GEN-LAST:event_formComponentShown

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        String loggedAdminID = this.controller.getLoggedInID();
        
        boolean isDeleted = this.controller.deleteAdministrator(ID, role) ; 
        String message = "" ; 
        
        if(isDeleted){
            
            message = "This " + this.role + " Has deleted Successfully" ; 
            JOptionPane.showMessageDialog(this, message,this.role +"Deleted", JOptionPane.INFORMATION_MESSAGE);
            
        } else{
            
            message = "Can't Preform The Deletion Only One "+ this.role + " Left" ; 
            JOptionPane.showMessageDialog(this, message,"Faild To Delete", JOptionPane.ERROR_MESSAGE); 
        }
        
        if(this.ID.equals(loggedAdminID) && this.role.equals(Role.Admin.name()) && isDeleted){
            
            this.dispose();
            new MainView().setVisible(true);
            
        } else{
            
            this.BackButtonActionPerformed(null) ; 
        }
        
    }//GEN-LAST:event_deleteActionPerformed

    @Override
    public final void setSpecialSettings() {
        
        this.setLocationRelativeTo(null);
    }
    
    @Override
    public void setController(Controller controller){
    
        this.controller = (AdministratorController) controller;
    }
    
    @Override
    public final void setPreviousFrame(JFrame previousFrame) {
        
        this.previousFrame = previousFrame;
    }
    
    @Override
    public javax.swing.JFrame getPreviousFrame(){
    
        return this.previousFrame;
    }
    
    private AdministratorController controller;
    private javax.swing.JFrame previousFrame;
    private String ID , role ; 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel confirmDeletionMessage;
    private javax.swing.JButton delete;
    private javax.swing.JLabel id;
    private javax.swing.JLabel idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel roleField;
    // End of variables declaration//GEN-END:variables
}
